using System;
using System.Collections.Generic;
using Apache.Cassandra;

namespace Lesula.Cassandra.FrontEnd
{
    public interface ISelector
    {
        CqlResult ExecuteCQL(string query);
        int GetColumnCount(string columnFamily, string rowKey, ConsistencyLevel consistencyLevel);
        int GetColumnCount(string columnFamily, byte[] rowKey, ConsistencyLevel consistencyLevel);
        int GetColumnCount(string columnFamily, string rowKey, SlicePredicate predicate, ConsistencyLevel consistencyLevel);
        int GetColumnCount(string columnFamily, byte[] rowKey, SlicePredicate predicate, ConsistencyLevel consistencyLevel);
        Column GetColumnFromRow(string columnFamily, string rowKey, string colName, ConsistencyLevel consistencyLevel);
        Column GetColumnFromRow(string columnFamily, ulong rowKey, string colName, ConsistencyLevel consistencyLevel);
        Column GetColumnFromRow(string columnFamily, string rowKey, byte[] colName, ConsistencyLevel consistencyLevel);
        Column GetColumnFromRow(string columnFamily, Guid rowKey, string colName, ConsistencyLevel consistencyLevel);
        Column GetColumnFromRow(string columnFamily, byte[] rowKey, byte[] colName, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<string, List<Column>>> GetColumnsAllRowsUtf8Keys(string columnFamily, int count, ConsistencyLevel consistencyLevel);
        List<Column> GetColumnsFromRow(string columnFamily, ulong rowKey, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<Column> GetColumnsFromRow(string columnFamily, ulong rowKey, bool reversed, ConsistencyLevel consistencyLevel);
        List<Column> GetColumnsFromRow(string columnFamily, string rowKey, bool reversed, ConsistencyLevel consistencyLevel);
        List<Column> GetColumnsFromRow(string columnFamily, string rowKey, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<Column> GetColumnsFromRow(string columnFamily, byte[] rowKey, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<Column> GetColumnsFromRow(string columnFamily, byte[] rowKey, bool reversed, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<Column>>> GetColumnsFromRows(string columnFamily, List<byte[]> rowKeys, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<Column>>> GetColumnsFromRows(string columnFamily, List<byte[]> rowKeys, bool reversed, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<Column>>> GetColumnsFromRows(string columnFamily, KeyRange keyRange, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<Column>>> GetColumnsFromRows(string columnFamily, KeyRange keyRange, bool reversed, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<string, List<Column>>> GetColumnsFromRowsUtf8Keys(string columnFamily, List<string> rowKeys, bool reversed, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<string, List<Column>>> GetColumnsFromRowsUtf8Keys(string columnFamily, List<string> rowKeys, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<string, List<Column>>> GetColumnsFromRowsUtf8Keys(string columnFamily, KeyRange keyRange, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<string, List<Column>>> GetColumnsFromRowsUtf8Keys(string columnFamily, KeyRange keyRange, bool reversed, ConsistencyLevel consistencyLevel);
        CounterColumn GetCounterColumnFromRow(string columnFamily, byte[] rowKey, byte[] colName, ConsistencyLevel consistencyLevel);
        List<CounterColumn> GetCounterColumnsFromRow(string columnFamily, byte[] rowKey, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<CounterColumn> GetCounterColumnsFromRow(string columnFamily, byte[] rowKey, bool reversed, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<CounterColumn>>> GetCounterColumnsFromRows(string columnFamily, List<byte[]> rowKeys, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<CounterColumn>>> GetCounterColumnsFromRows(string columnFamily, List<byte[]> rowKeys, bool reversed, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<CounterColumn>>> GetCounterColumnsFromRows(string columnFamily, KeyRange keyRange, bool reversed, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<string, List<CounterColumn>>> GetCounterColumnsFromRowsUtf8Keys(string columnFamily, List<string> rowKeys, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        long GetCounterColumnValueFromRow(string columnFamily, byte[] rowKey, byte[] colName, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<Column>>> GetIndexedColumns(string colParent, IndexClause indexClause, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<Column>>> GetIndexedColumns(string columnFamily, IndexClause indexClause, bool reversed, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<Column>>> GetIndexedColumns(ColumnParent colParent, IndexClause indexClause, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<Column>>> GetIndexedColumns(ColumnParent colParent, IndexClause indexClause, bool reversed, ConsistencyLevel consistencyLevel);
        List<byte[]> GetPageOfColumnNamesFromRow(string columnFamily, byte[] rowKey, byte[] startBeyondName, bool reversed, int count, ConsistencyLevel consistencyLevel);
        List<Column> GetPageOfColumnsFromRow(string columnFamily, string rowKey, string startBeyondName, bool reversed, int count, ConsistencyLevel consistencyLevel);
        List<Column> GetPageOfColumnsFromRow(string columnFamily, string rowKey, byte[] startBeyondName, bool reversed, int count, ConsistencyLevel consistencyLevel);
        List<Column> GetPageOfColumnsFromRow(string columnFamily, byte[] rowKey, string startBeyondName, bool reversed, int count, ConsistencyLevel consistencyLevel);
        List<Column> GetPageOfColumnsFromRow(string columnFamily, byte[] rowKey, byte[] startBeyondName, bool reversed, int count, ConsistencyLevel consistencyLevel);
        List<SuperColumn> GetPageOfSuperColumnsFromRow(string columnFamily, string rowKey, string startBeyondName, bool reversed, int count, ConsistencyLevel consistencyLevel);
        List<SuperColumn> GetPageOfSuperColumnsFromRow(string columnFamily, string rowKey, byte[] startBeyondName, bool reversed, int count, ConsistencyLevel consistencyLevel);
        List<SuperColumn> GetPageOfSuperColumnsFromRow(string columnFamily, byte[] rowKey, string startBeyondName, bool reversed, int count, ConsistencyLevel consistencyLevel);
        List<SuperColumn> GetPageOfSuperColumnsFromRow(string columnFamily, byte[] rowKey, byte[] startBeyondName, bool reversed, int count, ConsistencyLevel consistencyLevel);
        int GetSubColumnCount(string columnFamily, string rowKey, byte[] superColName, ConsistencyLevel consistencyLevel);
        int GetSubColumnCount(string columnFamily, byte[] rowKey, string superColName, ConsistencyLevel consistencyLevel);
        int GetSubColumnCount(string columnFamily, string rowKey, string superColName, ConsistencyLevel consistencyLevel);
        int GetSubColumnCount(string columnFamily, byte[] rowKey, byte[] superColName, ConsistencyLevel consistencyLevel);
        int GetSubColumnCount(string columnFamily, string rowKey, byte[] superColName, SlicePredicate predicate, ConsistencyLevel consistencyLevel);
        int GetSubColumnCount(string columnFamily, string rowKey, string superColName, SlicePredicate predicate, ConsistencyLevel consistencyLevel);
        int GetSubColumnCount(string columnFamily, byte[] rowKey, string superColName, SlicePredicate predicate, ConsistencyLevel consistencyLevel);
        int GetSubColumnCount(string columnFamily, byte[] rowKey, byte[] superColName, SlicePredicate predicate, ConsistencyLevel consistencyLevel);
        Column GetSubColumnFromRow(string columnFamily, string rowKey, string superColName, string subColName, ConsistencyLevel consistencyLevel);
        Column GetSubColumnFromRow(string columnFamily, string rowKey, byte[] superColName, string subColName, ConsistencyLevel consistencyLevel);
        Column GetSubColumnFromRow(string columnFamily, string rowKey, string superColName, byte[] subColName, ConsistencyLevel consistencyLevel);
        Column GetSubColumnFromRow(string columnFamily, string rowKey, byte[] superColName, byte[] subColName, ConsistencyLevel consistencyLevel);
        Column GetSubColumnFromRow(string columnFamily, byte[] rowKey, byte[] superColName, byte[] subColName, ConsistencyLevel consistencyLevel);
        List<Column> GetSubColumnsFromRow(string columnFamily, string rowKey, string superColName, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<Column> GetSubColumnsFromRow(string columnFamily, string rowKey, string superColName, bool reversed, ConsistencyLevel consistencyLevel);
        List<Column> GetSubColumnsFromRow(string columnFamily, string rowKey, byte[] superColName, bool reversed, ConsistencyLevel consistencyLevel);
        List<Column> GetSubColumnsFromRow(string columnFamily, string rowKey, byte[] superColName, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<Column> GetSubColumnsFromRow(string columnFamily, byte[] rowKey, byte[] superColName, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<Column> GetSubColumnsFromRow(string columnFamily, byte[] rowKey, byte[] superColName, bool reversed, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<Column>>> GetSubColumnsFromRows(string columnFamily, List<byte[]> rowKeys, byte[] superColName, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<Column>>> GetSubColumnsFromRows(string columnFamily, List<byte[]> rowKeys, string superColName, bool reversed, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<Column>>> GetSubColumnsFromRows(string columnFamily, List<byte[]> rowKeys, string superColName, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<Column>>> GetSubColumnsFromRows(string columnFamily, KeyRange keyRange, string superColName, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<Column>>> GetSubColumnsFromRows(string columnFamily, List<byte[]> rowKeys, byte[] superColName, bool reversed, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<Column>>> GetSubColumnsFromRows(string columnFamily, KeyRange keyRange, string superColName, bool reversed, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<Column>>> GetSubColumnsFromRows(string columnFamily, KeyRange keyRange, byte[] superColName, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<Column>>> GetSubColumnsFromRows(string columnFamily, KeyRange keyRange, byte[] superColName, bool reversed, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<string, List<Column>>> GetSubColumnsFromRowsUtf8Keys(string columnFamily, List<string> rowKeys, byte[] superColName, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<string, List<Column>>> GetSubColumnsFromRowsUtf8Keys(string columnFamily, List<string> rowKeys, string superColName, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<string, List<Column>>> GetSubColumnsFromRowsUtf8Keys(string columnFamily, List<string> rowKeys, string superColName, bool reversed, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<string, List<Column>>> GetSubColumnsFromRowsUtf8Keys(string columnFamily, KeyRange keyRange, string superColName, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<string, List<Column>>> GetSubColumnsFromRowsUtf8Keys(string columnFamily, List<string> rowKeys, byte[] superColName, bool reversed, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<string, List<Column>>> GetSubColumnsFromRowsUtf8Keys(string columnFamily, KeyRange keyRange, string superColName, bool reversed, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<string, List<Column>>> GetSubColumnsFromRowsUtf8Keys(string columnFamily, KeyRange keyRange, byte[] superColName, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<string, List<Column>>> GetSubColumnsFromRowsUtf8Keys(string columnFamily, KeyRange keyRange, byte[] superColName, bool reversed, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<CounterColumn>>> GetSubCounterColumnsFromRows(string columnFamily, List<byte[]> rowKeys, string superColName, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<CounterColumn>>> GetSubCounterColumnsFromRows(string columnFamily, List<byte[]> rowKeys, string superColName, bool reversed, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<CounterColumn>>> GetSubCounterColumnsFromRows(string columnFamily, List<byte[]> rowKeys, byte[] superColName, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<CounterColumn>>> GetSubCounterColumnsFromRows(string columnFamily, List<byte[]> rowKeys, byte[] superColName, bool reversed, ConsistencyLevel consistencyLevel);
        int GetSuperColumnCount(string columnFamily, string rowKey, ConsistencyLevel consistencyLevel);
        int GetSuperColumnCount(string columnFamily, byte[] rowKey, ConsistencyLevel consistencyLevel);
        int GetSuperColumnCount(string columnFamily, string rowKey, SlicePredicate predicate, ConsistencyLevel consistencyLevel);
        int GetSuperColumnCount(string columnFamily, byte[] rowKey, SlicePredicate predicate, ConsistencyLevel consistencyLevel);
        SuperColumn GetSuperColumnFromRow(string columnFamily, string rowKey, string superColName, ConsistencyLevel consistencyLevel);
        SuperColumn GetSuperColumnFromRow(string columnFamily, string rowKey, byte[] superColName, ConsistencyLevel consistencyLevel);
        SuperColumn GetSuperColumnFromRow(string columnFamily, byte[] rowKey, byte[] superColName, ConsistencyLevel consistencyLevel);
        List<SuperColumn> GetSuperColumnsFromRow(string columnFamily, string rowKey, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<SuperColumn> GetSuperColumnsFromRow(string columnFamily, string rowKey, bool reversed, ConsistencyLevel consistencyLevel);
        List<SuperColumn> GetSuperColumnsFromRow(string columnFamily, byte[] rowKey, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<SuperColumn> GetSuperColumnsFromRow(string columnFamily, byte[] rowKey, bool reversed, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<SuperColumn>>> GetSuperColumnsFromRows(string columnFamily, List<byte[]> rowKeys, bool reversed, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<SuperColumn>>> GetSuperColumnsFromRows(string columnFamily, List<byte[]> rowKeys, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<SuperColumn>>> GetSuperColumnsFromRows(string columnFamily, KeyRange keyRange, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<byte[], List<SuperColumn>>> GetSuperColumnsFromRows(string columnFamily, KeyRange keyRange, bool reversed, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<string, List<SuperColumn>>> GetSuperColumnsFromRowsUtf8Keys(string columnFamily, List<string> rowKeys, bool reversed, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<string, List<SuperColumn>>> GetSuperColumnsFromRowsUtf8Keys(string columnFamily, List<string> rowKeys, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<string, List<SuperColumn>>> GetSuperColumnsFromRowsUtf8Keys(string columnFamily, KeyRange keyRange, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        List<KeyValuePair<string, List<SuperColumn>>> GetSuperColumnsFromRowsUtf8Keys(string columnFamily, KeyRange keyRange, bool reversed, ConsistencyLevel consistencyLevel);
        IIterator<Column> IterateColumnsFromRow(string columnFamily, string rowKey, string startBeyondName, bool reversed, int batchSize, ConsistencyLevel consistencyLevel);
        IIterator<Column> IterateColumnsFromRow(string columnFamily, byte[] rowKey, byte[] startBeyondName, bool reversed, int batchSize, ConsistencyLevel consistencyLevel);
        IIterator<KeyValuePair<byte[], List<Column>>> IterateColumnsFromRows(string columnFamily, int batchSize, ConsistencyLevel consistencyLevel);
        IIterator<KeyValuePair<byte[], List<Column>>> IterateColumnsFromRows(string columnFamily, byte[] startBeyondKey, int batchSize, ConsistencyLevel consistencyLevel);
        IIterator<KeyValuePair<byte[], List<Column>>> IterateColumnsFromRows(string columnFamily, byte[] startBeyondKey, int batchSize, SlicePredicate colPredicate, ConsistencyLevel consistencyLevel);
        IIterator<SuperColumn> IterateSuperColumnsFromRow(string columnFamily, string rowKey, string startBeyondName, bool reversed, int batchSize, ConsistencyLevel consistencyLevel);
        IIterator<SuperColumn> IterateSuperColumnsFromRow(string columnFamily, byte[] rowKey, byte[] startBeyondName, bool reversed, int batchSize, ConsistencyLevel consistencyLevel);
        List<CqlRow> Search(string columns, string columnFamily, string query, int maxResults, ConsistencyLevel consistencyLevel);
    }
}